ci: update actions, simplify caching and global refactoring

diff --git a/.github/workflows/post-release-docker-hub-alpha.yml b/.github/workflows/post-release-docker-hub-alpha.yml
--- a/.github/workflows/post-release-docker-hub-alpha.yml
+++ b/.github/workflows/post-release-docker-hub-alpha.yml
@@ -8,16 +8,27 @@ on:
       - v*-alpha.*
 
 jobs:
-  build-and-release:
+  build-and-push:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
-
-      - name: login to Docker Hub
-        uses: docker/login-action@v1
+      - uses: actions/checkout@v4
+      - uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
+      - name: Build and push the latest alpha Docker image
+        run: |
+          export MDF_BRANCH_TAG=alpha
+          i=0
+          while ! make -C docker release version-tag branch-tag
+          do
+            if [[ ${i} -gt 20 ]]
+            then
+              echo "Failure for more than 10 minutes -> abort"
+              exit 1
+            fi
 
-      - name: build and release the latest alpha Docker image
-        run: MDF_BRANCH_TAG=alpha make -C docker release version-tag branch-tag
+            echo "Maybe the package is not available yet on NPM. Let's wait 30s..."
+            sleep 30
+            ((i=i+1))
+          done
